# Generated by Django 4.1.6 on 2023-02-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
